### ISSUE TITLE
A problem occurred configuring project ':react-native-chainway-rfid'.

### ISSUE THREAD

**Issue by shoaibarifArgonTech** [RyanGst/react-native-chainway-rfid#2]
A problem occurred configuring project ':react-native-chainway-rfid'.
> Configuration with name 'compile' not found

**Comment by RyanGst** [comment]
hey @shoaibarifArgonTech, i wrote this library a while ago, i don't have access to any device or way to debug it anymore. 

The error you're having is related to your gradle version, you can check more details here:https://github.com/gradle/gradle/issues/17051
